# Generated by Django 3.0.7 on 2021-02-24 09:01

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default=None, max_length=200)),
                ('email', models.EmailField(default=None, max_length=200)),
                ('phone', models.CharField(default=None, max_length=50)),
                ('message', models.CharField(default=None, max_length=1000)),
                ('date_of_contact', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DigitalMarket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(default=None, max_length=200)),
                ('femails', models.EmailField(default=None, max_length=200)),
                ('fphones', models.CharField(default=None, max_length=50)),
                ('passout', models.CharField(default=None, max_length=50)),
                ('city', models.CharField(default=None, max_length=50)),
                ('classes', models.CharField(default=None, max_length=50)),
                ('comment', models.CharField(default=None, max_length=50)),
                ('date_market', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FullStack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(default=None, max_length=200)),
                ('femails', models.EmailField(default=None, max_length=200)),
                ('fphones', models.CharField(default=None, max_length=50)),
                ('passout', models.CharField(default=None, max_length=50)),
                ('city', models.CharField(default=None, max_length=50)),
                ('classes', models.CharField(default=None, max_length=50)),
                ('upcomingBatch', models.CharField(default=None, max_length=50)),
                ('comment', models.CharField(default=None, max_length=50)),
                ('date_full', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default=None, max_length=200)),
                ('last_name', models.CharField(default=None, max_length=200)),
                ('email', models.EmailField(default=None, max_length=200)),
                ('phone', models.CharField(default=None, max_length=200)),
                ('pass_out', models.CharField(default=None, max_length=200)),
                ('stream', models.CharField(choices=[('BSc', 'BSc'), ('MBA', 'MBA'), ('BE / Btech IT', 'BE / Btech IT'), ('BE / Btech Computer', 'BE / Btech Computer'), ('BE / Btech Mechanical', 'BE / Btech Mechanical'), ('BE / Btech Civil', 'BE / Btech Civil'), ('MSC', 'MSC'), ('BE / Btech Electrical', 'BE / Btech Electrical'), ('BCom', 'BCom'), ('BE / Btech Electronics', 'BE / Btech Electronics'), ('MCA', 'MCA'), ('BCA', 'BCA'), ('Others', 'Others'), ('Career Counselling', 'Career Counselling')], default=None, max_length=100)),
                ('City', models.CharField(default=None, max_length=200)),
                ('Comment', models.CharField(default=None, max_length=200)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tap_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(default=None, max_length=500)),
                ('job_description', ckeditor.fields.RichTextField(default=None)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
